from Basic.Redaction.Precision.Basic_Precision_RQ2 import readBasicPrecisionRQ2
from Basic.Redaction.Robustness.Basic_Robustness_RQ3 import readBasicRobustness_RQ3
from Basic.Redaction.Speed.Basic_Speed_RQ1 import readBasicSpeedRQ1
from Basic.Redaction.Speed.Basic_Speed_Total_RQ0 import readBasicSpeedTotalRQ0


from BinKit.Redaction.Binkit_Precision_RQ2 import readBinkitPrecisionRQ2
from BinKit.Redaction.Binkit_Robustness_RQ3 import readBinkitRobustnessRQ3
from BinKit.Redaction.Binkit_Speed_RQ1 import readBinkitSpeedRQ1


from IoT.Redaction.IoT_Precision_RQ2 import readIoTPrecicionRQ2
from IoT.Redaction.IoT_Speed_RQ1 import readIoTSpeedRQ1

from Windows.Redaction.Windows_Precision_RQ2 import readWindowsPrecisionRQ2
from Windows.Redaction.Windows_Speed_RQ1 import readWindowsSpeedRQ1


