mkdir NORMAL_EMBEDS_2
7z e ../NORMAL_EMBEDS_2.zip PSS -r
cp PSS NORMAL_EMBEDS_2/simCG
mv PSS NORMAL_EMBEDS_2/simCFG

mkdir OBFUS_EMBEDS
7z e ../OBFUS_EMBEDS.zip PSS -r
cp PSS OBFUS_EMBEDS/simCG
mv PSS OBFUS_EMBEDS/simCFG
